services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    networks:
      - localprom
    volumes:
      - type: volume
        source: prometheus-volume
        target: /prometheus
      - type: bind
        source: ~/prometheus.yml
        target: /etc/prometheus/prometheus.yml
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: always
    privileged: true
    ports:
      - "9100:9100"
    networks:
      - localprom
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /run/systemd:/run/systemd:ro
      - /run:/run:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.arp
      - --collector.diskstats
      - --collector.filesystem
      - --collector.hwmon
      - --collector.interrupts
      - --collector.netdev
      - --collector.slabinfo
      - --collector.sysctl
      - --collector.systemd
      - --collector.buddyinfo
      - --collector.cgroups
      - --collector.cpu_vulnerabilities
      - --collector.meminfo_numa
      - --collector.mountstats
      - --collector.network_route
      - --collector.processes
      - --collector.softirqs
      - --collector.tcpstat
      - --collector.zoneinfo
      - --collector.ethtool
      - --collector.qdisc
      - --collector.wifi
      - --collector.xfrm
      - --collector.drm
      - --collector.drbd
      - --collector.ksmd
      - --collector.lnstat
      - --collector.logind
      - --collector.perf
      #- --collector.pcidevice
  pdc-agent:
    container_name: pdc-agent 
    image: grafana/pdc-agent
    restart: always
    networks:
      - localprom
    environment:
      TOKEN: ${TOKEN}
      CLUSTER: ${CLUSTER}
      GCLOUD_HOSTED_GRAFANA_ID: ${GCLOUD_HOSTED_GRAFANA_ID}
    command: >
      --token $TOKEN
      --cluster $CLUSTER
      --gcloud-hosted-grafana-id $GCLOUD_HOSTED_GRAFANA_ID

networks:
  localprom:
    driver: bridge

volumes:
  prometheus-volume:
